version: "3.9"
services:
  web:
    image: httpd:2.4-alpine
    container_name: apache-web
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/
    restart: unless-stopped
